// DP-Archives — project data (generated by Admin Panel)
window.DP_PROJECTS = [
  {
    "slug": "vaultify",
    "name": "Vaultify",
    "tagline": "Your Passwords. Secured. Simplified.",
    "description": "A desktop password manager designed to securely organize and manage passwords and other sensitive credentials in one convenient place.",
    "category": "Security",
    "status": "Live",
    "tech": [
      "Python",
      "Tkinter",
      "GUI",
      "Pandas",
      "Cryptography",
      "OpenPyXL"
    ],
    "featured": true,
    "updated": "2026-09-27",
    "url": "",
    "github": "https://github.com/DP-Archives/Vaultify",
    "accent": "#8b5cf6"
  },
  {
    "slug": "vortex",
    "name": "Vortex",
    "tagline": "AI Assistance, Right Where You Need It.",
    "description": "A discreet AI assistant that runs alongside your workflow and provides contextual help through a connection to Ollama and locally running AI models. Ollama provides a local API for interacting with models, including chat and text generation.",
    "category": "AI",
    "status": "Live",
    "tech": [
      "Python",
      "CustomTkinter",
      "Pystray",
      "pynput"
    ],
    "featured": false,
    "updated": "2026-09-27",
    "url": "",
    "github": "https://github.com/DP-Archives/VORTEX",
    "accent": "#06b6d4"
  },
  {
    "slug": "dp-codelabs",
    "name": "DP Codelabs",
    "tagline": "Learn Python. Build from the Ground Up.",
    "description": "A structured Python learning platform designed to take beginners from the fundamentals to a strong programming foundation through a complete, step-by-step course.",
    "category": "Programming",
    "status": "Live",
    "tech": [],
    "featured": true,
    "updated": "2026-09-27",
    "url": "https://dpcodelab.vercel.app/",
    "github": "",
    "accent": "#22c55e"
  },
  {
    "slug": "myarchive",
    "name": "MyArchive",
    "tagline": "Your School Journey, Organized.",
    "description": "A personal portfolio manager designed for students to organize and showcase their school achievements, projects, certificates, activities, experiences, and other milestones in one place.",
    "category": "Education",
    "status": "Live",
    "tech": [
      "HTML",
      "CSS",
      "JavaScript"
    ],
    "featured": false,
    "updated": "2026-09-27",
    "url": "https://getmyarchive.vercel.app/",
    "github": "",
    "accent": "#6366f6"
  },
  {
    "slug": "commerce-forge",
    "name": "Commerce Forge",
    "tagline": "Build Better. Pitch Stronger.",
    "description": "A collaborative guide for teams participating in competitions such as pitch decks and business challenges, focusing on effective teamwork, role distribution, idea development, presentation, and coordination.",
    "category": "Business",
    "status": "Live",
    "tech": [],
    "featured": false,
    "updated": "2026-09-27",
    "url": "https://commerce-forge-eight.vercel.app",
    "github": "",
    "preview": "",
    "features": [],
    "accent": "#f59e0b"
  },
  {
    "slug": "little-moment",
    "name": "Little-Moment",
    "tagline": "A Collection of Memories, Made with Love.",
    "description": "A personal memory website created to preserve and present special moments, memories, and experiences in a simple and heartfelt digital space.",
    "category": "Personal",
    "status": "Live",
    "tech": [],
    "featured": false,
    "updated": "2026-09-27",
    "url": "https://little-moment.vercel.app/",
    "github": "",
    "accent": "#ec4899"
  },
  {
    "slug": "diplomat-desk",
    "name": "Diplomat Desk",
    "tagline": "Your Digital Workspace for Diplomacy.",
    "description": "A digital workspace designed to help students prepare for and manage diplomatic simulations such as Model United Nations, with tools and resources for delegates.",
    "category": "Education",
    "status": "Live",
    "tech": [],
    "featured": false,
    "updated": "2026-09-27",
    "url": "https://diplomat-desk.vercel.app",
    "github": "",
    "accent": "#3b82f6"
  }
];
